### ISSUE TITLE
Unable to install plugin version 0.0.8 in Blender 2.93

### ISSUE THREAD

**Issue by kitaedesigns** [silverslade/aframe_blender_exporter#14]
Console Log
"
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'aframe_blender_exporter-0'

"

Same error returned with Blender 2.92

Maybe this is a python versioning problem?

**Comment by s-light** [comment]
this is an old one -
are you able to update and then try again with the current blender 3.0.1 and the current exporter version 0.0.8?

**Comment by tinogithub** [comment]
Hello,
having the same problem again in Blender 3.2.0 and 3.4.0 with aframe_blender_export version 0.0.9 and 0.0.10

Console log in Blender 3.4.0 with 0.0.10
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'aframe_blender_exporter-0'"

Console log in Blender 3.2.0 with 0.0.9
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'aframe_blender_exporter-0'

Thank you for you help.

**Comment by tinogithub** [comment]
Ok, I solved the problem myself.
The name of the zip-file and the containing folder may not include points as characters. Changing to underscore solves the problem.
