### ISSUE TITLE
Error activating gltf export single GLTF model.

### ISSUE THREAD

**Issue by SanctumVenture** [silverslade/aframe_blender_exporter#18]
```
Python: Traceback (most recent call last):
  File "C:\Users\llill\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\aframe_blender_exporter-dev_rebase\__init__.py", line 507, in execute
    return my_exporter.export()
  File "C:\Users\llill\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\aframe_blender_exporter-dev_rebase\export_aframe\__init__.py", line 1095, in export
    self.export_single_model()
  File "C:\Users\llill\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\aframe_blender_exporter-dev_rebase\export_aframe\__init__.py", line 803, in export_single_model
    filename = os.path.join(constants.DEST_RES, constants.PATH_ASSETS, "MainMesh")
AttributeError: module 'aframe_blender_exporter-dev_rebase.constants' has no attribute 'DEST_RES'

location: <unknown location>:-1
```

Error activating gltf export single GLTF model.
os: Windows 11
Blender version: 3.1

_Originally posted by @SanctumVenture in https://github.com/silverslade/aframe_blender_exporter/pull/17#issuecomment-1068262044_

**Comment by SanctumVenture** [comment]
fixed on: 8b3c8ebfa0480dbabf8b8073c75a48afc4dbcb1e
